config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'categories#index'

  resources :posts do 
  	resources :comments
  end

 
  get 'categories/dogs' ,to: 'categories#dogs'
  get 'categories/cats' ,to: 'categories#cats'
  get 'categories/rabbits' ,to: 'categories#rabbits'



     # createアクションに対応するルーティングを追加
  post "likes/:post_id/create" => "likes#create"

   # destroyアクションに対応するルーティングを追加
  post "likes/:post_id/destroy" => "likes#destroy"



       # createアクションに対応するルーティングを追加
  post "votes/:comment_id/create" => "votes#create"

   # destroyアクションに対応するルーティングを追加
  post "votes/:comment_id/destroy" => "votes#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :votes

  # モデルのスコープ機能とは、共通的に使うクエリをモデルのメソッドのように定義できる機能です。
  # こうすることにより、複雑なSQLを何度も書かなくてよくなり、可読性と保守性を向上させることができます。
  # クエリとは、簡単にいうとターミナルやコマンドプロンプトに表示されるSQLのことだと考えてもらって問題ないです。
  # ここでvotesの数で並び替える処理をscopeとして定義している。
  #scope :order_by_voute_count, ->  { eager_load(:votes).group("comments.id").order('count(votes.id) desc') }
  # eager_loadは外部結合ができるメソッドです。


  scope :order_by_voute_count, ->  { left_joins(:votes).group(:id).order('count(votes.id) desc') }
end

app/models/like.rb
class Like < ApplicationRecord
	validates :user_id ,{presence: true}
	validates :post_id ,{presence: true}
	has_one :post
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, ImageUploader

	belongs_to :user
	has_many :comments
	has_many :likes
	belongs_to :category
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		
	end

	def dogs	
		@posts = Post.all
		@dogs = Post.where(:category_id => 1)	
	end


	def cats
		@cats = Post.where(:category_id => 2)	
	end

		def rabbits
		@rabbits = Post.where(:category_id => 3)	
	end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_post
	before_action :find_comment ,only:[:show, :edit, :update, :destroy]
	before_action :authenticate_user!

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(post_params)
		@comment.user_id = current_user.id

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end



 	def destroy
 		@comment.destroy
 		redirect_to post_path(@post)
 	end


	private

	def post_params
		params.require(:comment).permit(:content)
	end

	def find_post
		@post = Post.find(params[:post_id])

	end

	def find_comment
		@comment = @post.comments.find(params[:id])
	end


end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  # before_actionに「:authenticate_user」を追加
  before_action :authenticate_user!, only:[:create,:destroy]
  

  # createアクションを追加
  def create
    @like = Like.new(user_id: current_user.id,  post_id: params[:post_id])
    @like.save
    # 投稿詳細ページにリダイレクト
    redirect_to("/posts/#{params[:post_id]}")
  end

    # destroyアクションを定義
  def destroy
    @like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    @like.destroy
    redirect_to("/posts/#{params[:post_id]}" )
  end

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post ,only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]

  def index
    if params[:category].blank?
    	@posts = Post.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @posts = Post.where(:category_id => @category_id)
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comments = @post.comments
    
    

    # 変数@likes_countを定義
    #モデルにリレーションを作ることでLikes.findなどとアクセスしなくても
    #以下の形でpostに紐づくlikeのレコードを取得することができる。
    #また、countメソッドを使うとレコードがない場合に0となってしまうので、countはviewで描画時に行う。
    #Railsでは0の扱いが難しいため。

    #⬇︎サインインしてない = current_userがnilなので、エラーになってしまう。⬇︎
    #@likes_count = Like.where(post_id: @post.id).count
    @likes = @post.likes
      
    #ruby on railsだけではなく、SQLの知識も必要です。
    # order_by_voutes_countはcommet.rb つまりmodeleで定義した
    # scopeを実行しているものです。scopeについてはmodel側のソースコード
    # で簡単に説明しています。
    @comments_by_votes = @post.comments.order_by_voute_count
   
    #自分がいいね！したレコードがあるかどうかのチェック。
    #current_user&.idの&(アンパサンド)がないとcurrent_userがnilのときにエラーがおきる。
    @my_like = @likes.find_by_user_id(current_user&.id)
		# @my_votes = Vote.where(user_id:current_user.id, comment_id:@post.comments.ids)
  end

  def new
  	@post = current_user.posts.build
    @categories = Category.all.map{ |c| [c.name, c.id]}

  end

  def create
  	@post = current_user.posts.build(post_params)
    @post.category_id = params[:category_id]

  	if @post.save
  		redirect_to post_path(@post)
  	else
  		render 'new'
  	end
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def update
    @post.category_id = params[:category_id]
  	if @post.update(post_params)
  		redirect_to post_path
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@post.destroy
  	redirect_to root_path
  end



  private
  def post_params
  	params.require(:post).permit(:id, :title, :description, :image, :category_id)
  end

  def find_post
  	@post = Post.find(params[:id])
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	  # before_actionに「:authenticate_user」を追加
  before_action :authenticate_user!, only:[:create,:destroy]


  # createアクションを追加
  def create
    @vote = Vote.new(user_id: current_user.id,  comment_id: params[:comment_id])
    @post_id = @vote.comment.post.id
    @vote.save
    # 投稿詳細ページにリダイレクト
    redirect_back(fallback_location: post_path(@post_id))
  end

    # destroyアクションを定義
  def destroy
    @vote = Vote.find_by(user_id: current_user.id)
    @post_id = @vote.comment.post.id
    @vote.destroy
    redirect_back(fallback_location: post_path(@post_id))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/categories/cats.html.erb
<h3>ネコ一覧</h3>
 <div class="center">
  <div class="row row-eq-height">
    
    <% @cats.each do |cat| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
       <div class="thumbnail message"> 
        <% if cat.image? %>
         <%= link_to (image_tag cat.image.url), cat  %>
        <% end %> 

         <div class="caption">
            <h3 clas="message-title"><%= cat.title %></h3>   
             <p><%= link_to "View message", post_path(cat),class:"btn btn-default" %></p>
              <div class="index_icons"> 
                <% if cat.likes.size >= 1 %>
                  <span class="fa fa-heart index_like-icon"></span><%= cat.likes.size %> 
                <% else %>
                  <span class="fa fa-heart index_like-icon_zero"></span><%= cat.likes.size %>
                <% end %>

                <span style="margin-right: 25px;"></span>

               <% if cat.comments.size >= 1 %>
                  <span class="fa fa-comments-o index_comments-icon"></span><%= cat.comments.size %>  
                <% else %>
                  <span class="fa fa-comments-o index_comments-icon_zero"></span><%= cat.comments.size %> 
                <% end %>
            </div>
          </div> 


       </div><!-- end of thumbnail -->
      </div><!-- end of col-xs-12 col-sm-6 col-md-4 -->
     <% end %> 
  </div><!-- end of row row-eq-height -->
  <p><%= link_to "一覧に戻る", root_path,class:"btn btn-default" %></p>
</div><!-- end of center -->


<!-- このスクリプトは、bootatrapでドロップダウンなどを出すときに必要-->
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
         <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
         <script>
           $('.dropdown-toggle').dropdown()
  </script>

app/views/categories/dogs.html.erb
<h3>犬一覧</h3>
 <div class="center">
  <div class="row row-eq-height">
    
    <% @dogs.each do |dog| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
       <div class="thumbnail message"> 
        <% if dog.image? %>
         <%= link_to (image_tag dog.image.url), dog  %>
        <% end %> 

         <div class="caption">
            <h3 clas="message-title"><%= dog.title %></h3>   
             <p><%= link_to "詳細を見る", post_path(dog),class:"btn btn-default" %></p>
              <div class="index_icons"> 
                <% if dog.likes.size >= 1 %>
                  <span class="fa fa-heart index_like-icon"></span><%= dog.likes.size %> 
                <% else %>
                  <span class="fa fa-heart index_like-icon_zero"></span><%= dog.likes.size %>
                <% end %>

                <span style="margin-right: 25px;"></span>

               <% if dog.comments.size >= 1 %>
                  <span class="fa fa-comments-o index_comments-icon"></span><%= dog.comments.size %>  
                <% else %>
                  <span class="fa fa-comments-o index_comments-icon_zero"></span><%= dog.comments.size %> 
                <% end %>
            </div>
          </div> 


       </div><!-- end of thumbnail -->
      </div><!-- end of col-xs-12 col-sm-6 col-md-4 -->
     <% end %> 
  </div><!-- end of row row-eq-height -->
   <p><%= link_to "一覧に戻る", root_path,class:"btn btn-default" %></p>
</div><!-- end of center -->




<!-- このスクリプトは、bootatrapでドロップダウンなどを出すときに必要-->
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
         <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
         <script>
           $('.dropdown-toggle').dropdown()
  </script>

app/views/categories/index.html.erb
<h3>ペットの種類一覧</h3>
<div class="center">
  <div class="row row-eq-height">
  	<div class="col-xs-12 col-sm-6 col-md-4">
      <div class="thumbnail message"> 
				<%= image_tag 'dogs.jpg'%>
				<div class="caption">
	        <h3 clas="message-title">犬</h3>
	        <p><%= link_to "詳細を見る", categories_dogs_path,class:"btn btn-default" %></p>
	      </div> 
       </div><!-- end of thumbnail -->
    </div><!-- end of col-xs-12 col-sm-6 col-md-4 -->

		 <div class="col-xs-12 col-sm-6 col-md-4">
      <div class="thumbnail message cats"> 
				<%= image_tag 'cats.png' %>
				<div class="caption">
	        <h3 clas="message-title">ネコ</h3>
	        <p><%= link_to "詳細を見る", categories_cats_path,class:"btn btn-default" %></p>
	      </div> 
       </div><!-- end of thumbnail -->
    </div><!-- end of col-xs-12 col-sm-6 col-md-4 -->

			<div class="col-xs-12 col-sm-6 col-md-4">
      <div class="thumbnail message rabbits"> 
				<%= image_tag 'rabbits.jpg' %>
				<div class="caption">
	        <h3 clas="message-title">ウサギ</h3>
	        <p><%= link_to "詳細を見る", categories_rabbits_path,class:"btn btn-default" %></p>
	      </div> 
       </div><!-- end of thumbnail -->
    </div><!-- end of col-xs-12 col-sm-6 col-md-4 -->


  </div><!-- end of row row-eq-height -->
</div><!-- end of center -->



<!-- このスクリプトは、bootatrapでドロップダウンなどを出すときに必要-->
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
         <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
         <script>
           $('.dropdown-toggle').dropdown()
  </script>

app/views/categories/rabbits.html.erb
<h3>ウサギ一覧</h3>
 <div class="center">
  <div class="row row-eq-height">
    
    <% @rabbits.each do |rabbit| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
       <div class="thumbnail message"> 
        <% if rabbit.image? %>
         <%= link_to (image_tag rabbit.image.url), rabbit  %>
        <% end %> 

         <div class="caption">
            <h3 clas="message-title"><%= rabbit.title %></h3>   
             <p><%= link_to "詳細を見る", post_path(rabbit),class:"btn btn-default" %></p>
              <div class="index_icons"> 
                <% if rabbit.likes.size >= 1 %>
                  <span class="fa fa-heart index_like-icon"></span><%= rabbit.likes.size %> 
                <% else %>
                  <span class="fa fa-heart index_like-icon_zero"></span><%= rabbit.likes.size %>
                <% end %>

                <span style="margin-right: 25px;"></span>

               <% if rabbit.comments.size >= 1 %>
                  <span class="fa fa-comments-o index_comments-icon"></span><%= rabbit.comments.size %>  
                <% else %>
                  <span class="fa fa-comments-o index_comments-icon_zero"></span><%= rabbit.comments.size %> 
                <% end %>
            </div>
          </div> 


       </div><!-- end of thumbnail -->
      </div><!-- end of col-xs-12 col-sm-6 col-md-4 -->
     <% end %> 
  </div><!-- end of row row-eq-height -->
  <p><%= link_to "一覧に戻る", root_path,class:"btn btn-default" %></p>
</div><!-- end of center -->


<!-- このスクリプトは、bootatrapでドロップダウンなどを出すときに必要-->
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
         <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
         <script>
           $('.dropdown-toggle').dropdown()
  </script>

app/views/comments/_comment.html.erb
<!-- この_comment.html.erbは_formに記述した内容がpostsのshowページに表示される。 -->
<div class="comments_box">
	<p><%= comment.content %></p><br>
	<p class="message-posted-by"><%= time_ago_in_words(comment.created_at) %> 前 <%= comment.user.username %>  さんによって投稿されました。</p>
	<div class="like_button posts-show-item">
			<%if current_user.present? && comment.votes.where(user_id:current_user.id).present?%>
				<%comment.votes.where(user_id:current_user.id).each do |my_vote|%>
	       <%= link_to("/votes/#{my_vote.id}/destroy",{method: "post"})do %>
	        <span class="fa fa-thumbs-o-up vote-btn-donwvote"></span>
	       <% end %>
				<% end %>
      <% else %>
	      <%= link_to("/votes/#{comment.id}/create", {method: "post"}) do %>
	        <span class="fa fa-thumbs-o-up vote-btn"></span>
	      <% end %>
      <% end %>
      <%= comment.votes.count  %>
	</div>


	<% if user_signed_in? %>
		<% if comment.user_id == current_user.id %>
		<%= link_to "削除", post_comment_path(comment.post, comment), method: :delete, data:{confirm: "Are you sure?"} %>
		<% end %>
	<% end %>


</div>

app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build])do |form| %>


  <div class="form-group">
    <%= form.label :content,"コメント欄" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "コメントを投稿", class:"btn btn-primary" %>
  </div>
<% end %>



<!-- このスクリプトは、bootatrapでドロップダウンなどを出すときに必要-->
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
         <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
         <script>
           $('.dropdown-toggle').dropdown()
  </script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Pet Ranking", root_path,class:"navbar-brand" %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav"> 
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">動物の種類を選択<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
            <li class="<% 'active' if params[:category] == category.name %>">
              <%= link_to category.name, posts_path(category:category.name)%> </li><% end %>
          </ul>
        </li>           
        <% if user_signed_in? %>    
          <li><%= link_to "新規投稿", new_post_path %></li>            
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>

    
      <ul class="nav navbar-nav navbar-right ">
        <% if user_signed_in? %>
        <li><%= link_to "設定編集", edit_user_registration_path %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path,method: :delete %></li>
         <% end %>  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pet Ranking ポートフォリオ</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <!-- FontAwesomeを読み込むlinkタグを追加してください -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="shortcut icon" type="image/png" href="/assets/favicon.png">
    <meta charset="UTF-8"> <meta name=viewport content="width=device-width, initial-scale=1">
  </head>

  <body>
		<%= render 'layouts/header' %>

    <div class="container">
       <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">×</a> <!-- アラートダイアログに×ボタンをつける -->
          <%= msg %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, html: {multipart: true}) do |form| %>

    <div class="form-group">
    <%= form.label :動物の種類 %>
    <%= select_tag :category_id, options_for_select(@categories), prompt: "種類を選んでください",class: "form-control"  %>
   </div>
  <div class="form-group">
    <%= form.label :動物の名前 %>
    <%= form.text_field :title,class: "form-control" %>
  </div>

    <div class="form-group">
    <%= form.label :動物の詳細 %>
    <%= form.text_area :description,class: "form-control" %>
  </div>

    <div class="form-group">
    <%= form.label :画像 %>
    <%= form.file_field :image,class: "form-control" %>
  </div>

  

  <div class="actions">
    <%= form.submit "新規登録", class:"btn btn-primary"%>
  </div>
<% end %>



<!-- このスクリプトは、bootatrapでドロップダウンなどを出すときに必要-->
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
         <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
         <script>
           $('.dropdown-toggle').dropdown()
  </script>

app/views/posts/edit.html.erb
<h1>Edit page</h1>



<%= render 'form' %>

app/views/posts/index.html.erb
<h3><%= params[:category] %></h3>
 <div class="center">
  <div class="row row-eq-height">
    <% if @posts.count == 0 %>
    <h3>There are posts in this category yet </h3>
    <% else %>
    <% @posts.each do |post| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="thumbnail message"> 
            <% if post.image? %>
              <%= link_to (image_tag post.image.url), post %>
            <% end %>       
         
          <div class="caption">
          <h3 clas="message-title"><%= post.title %></h3>   
          <p><%= link_to "詳細を見る", post_path(post),class:"btn btn-default" %></p>
            <div class="index_icons"> 
              <% if post.likes.size >= 1 %>
                <span class="fa fa-heart index_like-icon"></span><%= post.likes.size %> 
              <% else %>
                <span class="fa fa-heart index_like-icon_zero"></span><%= post.likes.size %>
              <% end %>

              <span style="margin-right: 25px;"></span>

             <% if post.comments.size >= 1 %>
                <span class="fa fa-comments-o index_comments-icon"></span><%= post.comments.size %>  
              <% else %>
                <span class="fa fa-comments-o index_comments-icon_zero"></span><%= post.comments.size %> 
              <% end %>
          </div>
        </div>
       </div> 

      </div>
    <% end %>
    <% end %>
  </div>
 <p><%= link_to "一覧に戻る", root_path,class:"btn btn-default" %></p>
</div>



<!-- このスクリプトは、bootatrapでドロップダウンなどを出すときに必要-->
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
         <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
         <script>
           $('.dropdown-toggle').dropdown()
  </script>

app/views/posts/new.html.erb
<h1>ペット新規登録</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="message-show">
	<br>
	<div class="row">
	  <div class="col-md-4">
		<%= image_tag @post.image_url,class:"show-pic-size"  %>
	<h2><%= @post.title %></h2>
	<p class="message-posted-by"><%= time_ago_in_words (@post.created_at) %> 前  <%= @post.user.username %> さんによって投稿されました。</p>
	<p>種類: <%= @post.category.name %></p>

					<div class="like_button posts-show-item">
				 <!-- if文を用いて、表示内容を切り替え -->
						<%if @my_like.present? %>
				      <%= link_to("/likes/#{@post.id}/destroy",{method: "post"})do %>
				        <span class="fa fa-heart like-btn-unlike btn btn-default btn-round"></span>
				      <% end %>
			      <% else %>
				      <%= link_to("/likes/#{@post.id}/create", {method: "post"}) do %>
				        <span class="fa fa-heart like-btn btn btn-default btn-round"></span>
				      <% end %>
			      <% end %>
			      <%= @likes.count  %>
				</div>
		</div>

    <div class="visible-xs visible-sm" style="height:30px;"></div>


      <!-- ここからshowの右画面 -->
    <div class="col-md-7 col-md-offset-1 ">
				<p><%= @post.description %></p>
		</div><!-- end of col-md-7 col-md-offset-1 -->

	</div><!-- row -->

<br><hr>


	<% if @comments_by_votes.length >= 2 %>
		<h3>コメント<%= @comments_by_votes.length %> 件:</h3>
		<% else %>
			<h3>コメント<%= @comments_by_votes.length %> 件:</h3>
	<% end %>
	<%= render @comments_by_votes %>
	

	<h3 class="reply-to-message">コメントを書く:</h3>
	<%= render 'comments/form' %>

	<div class="btn-group">
		<%= link_to "一覧に戻る", root_path, class:"btn btn-default" %>
		<% if user_signed_in? %>
			<% if @post.user_id == current_user.id %>
				<%= link_to "編集", edit_post_path(@post), class:"btn btn-success" %>
				<%= link_to "削除", post_path(@post), method: :delete, data:{confirm: "Are you sure?" }, class:"btn btn-danger" %>
			<% end %>
		<% end %>
		</div>
	</div>
	<br><br><br><br>